name: Full CI
on:
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/node-workflow.yml
    with:
      use-matrix: true
      run-command: pnpm run test:large
      command-description: Test
